### ISSUE TITLE
Example App not working

### ISSUE THREAD

**Issue by franz-josef-kaiser** [tbosch/phonecat-mobile#1]
neither on desktop, nor on mobile.

**Comment by stefanscheidt** [comment]
Can you give us some more information? What did you do? The following works on my machine and on our CI server:

git clone repo
$ mvn jetty:run
open http://localhost:8080/phonecat-mobile/ in my browser (Chrome, Safari).

Which problems do occur?

**Comment by tbosch** [comment]
Hi,
yes I see that the live demo is no more working.We didn't update this project for some time, sorry about that.

If you are interested in a demo for the jquery-mobile-angular-adapter or the sencha-touch-angular-adapter, please have a look at tibgro/todo-mobile.

If you are interested in a sample for jasmine-ui, please have a look at stefanscheidt/js-fadein.

However, I will update this project in the next week to it should work then.

Thanks for the hint!

Tobias

**Comment by franz-josef-kaiser** [comment]
n/p

**Comment by tbosch** [comment]
The live versions should work now again, including the unit and ui-tests.
Also upgraded to the current versions of requirejs and jquery-mobile.

Tobias
